"""
Contains all the required and optional (docs, testing etc.) dependencies.
should be the same as pip install c3s_sm[complete]
"""
name: c3s_sm
channels:
  - conda-forge
  - defaults
dependencies:
  - python>=3.8,<=3.12
  - pandas
  - netcdf4
  - pyresample
  - matplotlib
  - xarray
  - dask
  - ipykernel
  - pip
  - pip:
    - pygeobase
    - pynetcf>=0.2.2
    - repurpose>=0.11
    - parse
    - cadati
    - smecv_grid>=0.3
    - more_itertools
    - cdsapi
    - click
    - pytest
    - pytest-cov