name: c3s_sm
channels:
  - conda-forge
  - defaults
dependencies:
  - pandas
  - netcdf4
  - pyresample
  - pip
  - pip:
    - pygeobase
    - pynetcf>=0.2.2
    - repurpose
    - parse
    - cadati
    - smecv_grid==0.3
    - more_itertools
    - pytest
    - pytest-cov
    - sphinx_rtd_theme
