name: c3s_sm
channels:
  - defaults
dependencies:
  - netcdf4=1.2.2
  - numpy
  - pandas
  - scipy
  - pytest=3.1.2
  - pip:
    - pynetcf
    - repurpose
    - pytesmo
    - pyresample
    - parse
    - pytest-cov==2.2.1
    # - smecv_grid #### when public